ignoreFields:
  - fields:
    - metadata.namespace
    objects:
    - kind: '*'
  - fields:
    - spec.containers.*.imagePullPolicy
    - spec.containers.*.terminationMessagePath
    - spec.containers.*.terminationMessagePolicy
    - spec.containers.*.volumeMounts.*
    - spec.volumes.*.projected.*
    - spec.tolerations.*
    - spec.dnsPolicy
    - spec.terminationGracePeriodSeconds
    - spec.enableServiceLinks
    - spec.preemptionPolicy
    - spec.priority
    - spec.restartPolicy
    - spec.schedulerName
    - spec.serviceAccount
    objects:
    - kind: Pod