name: image
on:
  push:
    branches:
      - 'main'
      - 'release*'

permissions:
  contents: read
  packages: write
  id-token: write 

jobs:
  push-init-kyverno:
    uses: namanl2001/kyverno/.github/workflows/reuse.yaml@release-1.9
    with:
      publish_command: docker-publish-initContainer
      digest_command: docker-get-initContainer-dev-digest
      image_name: kyvernopre
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno:
    uses: namanl2001/kyverno/.github/workflows/reuse.yaml@release-1.9
    with:
      publish_command: docker-publish-kyverno
      digest_command: docker-get-kyverno-dev-digest
      image_name: kyverno
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno-cli:
    uses: namanl2001/kyverno/.github/workflows/reuse.yaml@release-1.9
    with:
      publish_command: docker-publish-cli
      digest_command: docker-get-cli-dev-digest
      image_name: kyverno-cli
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}