name: image
on:
  push:
    tags:
      - 'v*'

jobs:
  push-init-kyverno:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.0'

      - name: login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: docker images publish
        run: |
          make docker-publish-initContainer-dev
      - name: get digest
        id: get-step
        run: |
          echo "::set-output name=digest::$(make docker-get-initContainer-digest)"
      - name: Sign image
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign \
          -a "repo=${{ github.repository }}" \
          -a "workflow=${{ github.workflow }}" \
          -a "ref=${{ github.sha }}" \
          ghcr.io/namanl2001/kyvernopre@sha256:${{ steps.get-step.outputs.digest }}


  push-kyverno:
    uses: Namanl2001/kyverno/.github/workflows/reuse.yaml@va.b.c
    with:
      publish_command: docker-publish-kyverno-dev
      digest_command: docker-get-kyverno-dev-digest
      image_name: kyverno
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  push-kyverno-cli:
    uses: Namanl2001/kyverno/.github/workflows/reuse.yaml@va.b.c
    with:
      publish_command: docker-publish-cli-dev
      digest_command: docker-get-cli-dev-digest
      image_name: kyverno-cli
      tag: image
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}
