name: releaser
on:
  push:
    tags:
      - 'v*'
jobs:
  release-init-kyverno:
    uses: Namanl2001/kyverno/.github/workflows/reuse.yaml@va.b.c
    with:
      publish_command: docker-publish-initContainer
      digest_command: docker-get-initContainer-digest
      image_name: kyvernopre
      tag: release
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  release-kyverno:
    uses: Namanl2001/kyverno/.github/workflows/reuse.yaml@va.b.c
    with:
      publish_command: docker-publish-kyverno
      digest_command: docker-get-kyverno-digest
      image_name: kyverno
      tag: release
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}

  release-kyverno-cli:
    uses: Namanl2001/kyverno/.github/workflows/reuse.yaml@va.b.c
    with:
      publish_command: docker-publish-cli
      digest_command: docker-get-cli-digest
      image_name: kyverno-cli
      tag: release
    secrets:
      registry_username: ${{ github.actor }}
      registry_password: ${{ secrets.CR_PAT }}
  
  create-release:
    runs-on: ubuntu-latest
    needs:
      - release-init-kyverno
      - release-kyverno
      - release-kyverno-cli
    steps:
      - name: Set version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
            
      - uses: creekorful/goreportcard-action@v1.0

      - name: Make Release
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          rm -rf release
          mkdir release
          make release-notes > release/release-notes.out
          cat release/release-notes.out
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --debug --release-notes=release/release-notes.out
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-cli-via-krew:
    runs-on: ubuntu-latest
    needs: 
    - create-release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo ::set-output name=match::true
          fi

      - name: Update new version in krew-index
        if: steps.check-tag.outputs.match == 'true'
        uses: rajatjindal/krew-release-bot@v0.0.38
